YT_Django_course_Son_Nguyen/user_authentication/Authen/Authen/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Login.urls'))
]

YT_Django_course_Son_Nguyen/user_authentication/Authen/Login/urls.py
from django.urls import path
from .views import AddPost, IndexClass, LoginClass, ViewUser, view_product

app_name = 'Login'
urlpatterns = [
    path('', IndexClass.as_view(), name='index'),
    path('login/', LoginClass.as_view(), name='login'),
    path('user-view/', ViewUser.as_view(), name='user_view'),
    path('view-pro/', view_product, name='view-product'),
    path('add-post', AddPost.as_view(), name='add_post')
]

YT_Django_course_Son_Nguyen/user_authentication/Authen/Login/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=100)
    content = models.CharField(max_length=225)
    
    def __str__(self):
        return self.title
    
    
class MyUser(AbstractUser):
    sex_choice = ((0, 'Nữ'), (1, 'Nam'), (3, 'Không xác định'))
    age = models.IntegerField(default=0)
    sex = models.IntegerField(choices=sex_choice, default=0)
    address = models.CharField(default='', max_length=255)

YT_Django_course_Son_Nguyen/user_authentication/Authen/Login/forms.py
from django.core import files
from django.forms import ModelForm
from .models import Post


class PostForm(ModelForm):
    class Meta:
        model = Post
        fields = ('title', 'content')

YT_Django_course_Son_Nguyen/user_authentication/Authen/Login/views.py
from django.shortcuts import render, HttpResponse
from django.views import View
from django.contrib.auth import authenticate, login, decorators
from django.contrib.auth.mixins import LoginRequiredMixin
from .forms import PostForm
# Create your views here.


class IndexClass(View):
    def get(self, request):
        return HttpResponse("<h1>Hello</h1>")


class LoginClass(View):
    def get(self, request):
        return render(request, 'Login/login.html')
    
    def post(self, request):
        user_name = request.POST.get('tendangnhap') # get username from file login.html
        password = request.POST.get('password') # get password from file login.html
        my_user = authenticate(username=user_name, password=password) # check username and password
        
        if my_user is None: # if this user does not exist
            return HttpResponse("This user does not exist")
        
        
        # this user exists on database
        login(request, my_user) # login with this user
        return render(request, 'Login/thanhcong.html')
    
    
class ViewUser(LoginRequiredMixin, View): # only user who is logged in can access these views in this class
    login_url = '/login/' # user will be redirected to this url if he/she is not logged in
    def get(self, request):
            return HttpResponse("<h1>This is user view</h1>")
        
    def post(self, request):
        pass
        
        
# if user go to this url without login, it will redirect to login page
@decorators.login_required(login_url='/login/')
def view_product(request):
    # only valid user can access this url
    return HttpResponse("View product")


class AddPost(LoginRequiredMixin, View):
    login_url = '/login/' # user will be redirected to this url if he/she is not logged in
    def get(self, request):
        f = PostForm()
        context = {
            'fm': f
        }
        
        return render(request, 'Login/add_post.html', context)
    
    
    def post(self, request):
        f = PostForm(request.POST)
        
        if not f.is_valid():
            return HttpResponse("Invalid form")
        
        # print(request.user.get_all_permissions()) # get all permission of this user
        if request.user.has_perm('Login.add_post'): # model name have to be lower-case
            # user has permission to add post
            # save data into database
            f.save()
        else:
            return HttpResponse("You do not have permission to add post")
        return HttpResponse('OK')

YT_Django_course_Son_Nguyen/user_authentication/Authen/Login/templates/Login/add_post.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <form action="{% url 'Login:add_post' %}" method="post">
        {% csrf_token %}
        {{ fm }}
        <input type="submit" value="ADD">
    </form>
</body>
</html>

YT_Django_course_Son_Nguyen/user_authentication/Authen/Login/templates/Login/login.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>Title</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="">
    </head>
    <body>
        <div class="Login">
            <form action="" method="post">
                {% csrf_token %}
                <input type="text" name="tendangnhap">
                <input type="password" name="password">
                <input type="submit" value="Log in">
            </form>
        </div>
        <script src="" async defer></script>
    </body>
</html>

YT_Django_course_Son_Nguyen/user_authentication/Authen/Login/templates/Login/thanhcong.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login success</title>

    <style>
        .message {
            color: red;
        }
    </style>
</head>
<body>
    <div class="message">
        <h3>Login success.</h3>
    </div>
</body>
</html>