django_ajax/posts/urls.py
from django.urls import path
from .views import (
    post_list_and_created,
    load_post_data_view,
    like_unlike_post,
    hello_world_view,
)


app_name = 'posts'
urlpatterns = [
    path('', post_list_and_created, name='main-board'),
    path('data/<int:num_posts>/', load_post_data_view, name='posts-data'),
    path('like-unlike/', like_unlike_post, name='like-unlike'),
    
    path('hello-world/', hello_world_view, name='hello-world'),
]

django_ajax/posts_proj/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('posts.urls', namespace='posts')),
]

urlpatterns += static(
    settings.STATIC_URL,
    document_root=settings.STATIC_ROOT
)

urlpatterns += static(
    settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT
)

django_ajax/posts/models.py
from django.db import models
from django.contrib.auth.models import User
from profiles.models import Profile

# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=100)
    body = models.TextField()
    liked = models.ManyToManyField(User, blank=True)
    author = models.ForeignKey(Profile, on_delete=models.CASCADE)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)
    
    
    def __str__(self) -> (str):
        return str(self.title)
    
    
    @property
    def like_count(self):
        return self.liked.all().count()

django_ajax/profiles/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    bio = models.TextField(blank=True)
    avatar = models.ImageField(default='avatar.png', upload_to= 'avatars')
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)
    
    
    def __str__(self) -> (str):
        return f"Profile of the user {self.user.username}"

django_ajax/posts/views.py
from django.http import JsonResponse
from django.shortcuts import render
from .models import Post
from django.core import serializers

# Create your views here.
def post_list_and_created(request):
    qs = Post.objects.all() # get all posts in the database
    return render(request, 'posts/main.html', {
        'qs': qs
    })
    
    
def load_post_data_view(request, num_posts):
    visible = 3
    upper = num_posts
    lower = upper - visible 
    size = Post.objects.all().count()
    qs = Post.objects.all()
    data = []
    for obj in qs:
        item = {
            'id': obj.id,
            'title': obj.title,
            'body': obj.body,
            'liked': True if request.user in obj.liked.all() else False,
            'count': obj.like_count,
            'author': obj.author.user.username   
        }
        data.append(item)
        
    return JsonResponse({'data': data[lower:upper], 'size': size})
    
def like_unlike_post(request):
    if request.is_ajax():
        pk = request.POST.get('pk')
        obj = Post.objects.get(pk=pk)
        
        if request.user in obj.liked.all(): # if this user liked this post before, remove him from the list
            liked = False
            obj.liked.remove(request.user)
        else: # if this is the fist time this user like this port, add him to the list
            liked = True
            obj.liked.add(request.user)
            
        return JsonResponse({'liked': liked, 'count': obj.like_count})
        
    
def hello_world_view(request):
    return JsonResponse({
        'text': 'Manh Cuong is too cool, handsome'
    })

django_ajax/profiles/views.py
from django.shortcuts import render

# Create your views here.

django_ajax/posts/templates/posts/main.html
{% extends 'base.html' %}

{% load static %}

{% block scripts %}
  <!-- defer parameter is used to delay js code until the page is completely loaded -->
  <script src="{% static 'posts/main.js' %}" defer></script>
{% endblock scripts %}
posts
{% block title %}
{% endblock title %}

{% block content %}
  <!-- Modal -->
  <div class="modal fade" id="addPostModel" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Create post</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          ...
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-danger" data-bs-dismiss="modal">close</button>
          <button type="button" class="btn btn-success">+ add</button>
        </div>
      </div>
    </div>
  </div>

  <!-- Button trigger modal -->
  <button type="button" id="addPostModal" class="btn btn-info mb-2" data-bs-toggle="modal" data-bs-target="#addPostModel">
    add post
  </button>
  
  <div id="posts-box"></div>
  
  <div id="spinner-box" class="text-center">
    <div class="spinner-border" role="status"></div>
  </div>

  <div class="text-center mb-3" id="end-box">
    <button class="btn btn-primary" id="load-btn">Load more</button>
  </div>
{% endblock content %}

django_ajax/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />

    <!-- favicon -->
    <link rel="icon" type="image/png" href="{% static 'favicon.ico' %}" />

    <!-- Bootstrap CSS -->
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl"
      crossorigin="anonymous"
    />

    <!-- Custom css -->
    <link rel="stylesheet" href="{% static 'style.css' %}" />

    <!-- dropzone -->
    <link rel="stylesheet" href="{% static 'dropzone.css' %}" />
    <script src="{% static 'dropzone.js' %}" defer></script>

    <!-- Custom js -->
    <script src="{% static 'functions.js' %}" defer></script>
    {% block scripts %} {% endblock scripts %}

    <title>read posts | {% block title %}{% endblock title %}</title>
  </head>
  <body>
    {% include "navbar.html" %}
    <div class="container mt-3 mb-3">
      {% block content %} {% endblock content %}
    </div>

    <!-- Bootstrap Bundle with Popper -->
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0"
      crossorigin="anonymous"
    ></script>
    <!-- Jquery -->
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
  </body>
</html>

django_ajax/templates/navbar.html
{% url 'posts:main-board' as path_to_home %}
{% url 'profiles:my-profile' as path_to_my_profile %}

<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="{{path_to_home}}">Posts-proj</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link {% if request.path == path_to_home %}active{% endif %}" aria-current="page" href="{{path_to_home}}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link {% if request.path == path_to_my_profile %}active{% endif %}" href="{{path_to_my_profile}}">My Profile</a>
        </li>
      </ul>
    </div>
  </div>
</nav>